export const LIMITS = {
  MAX_SENTENCE_LENGTH: 25,
  MAX_PARAGRAPH_SENTENCES: 4,
  MIN_PARAGRAPH_WORDS: 40,
  MAX_KEYWORD_DENSITY: 2.5,
  MAX_REPETITION_RATE: 0.08
};

export const SEVERITY = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high"
};

export const SCORE_WEIGHTS = {
  LONG_SENTENCE: 2,
  VERY_LONG_SENTENCE: 4,
  DENSE_PARAGRAPH: 5,
  SHORT_PARAGRAPH: 2,
  REPETITION: 6,
  KEYWORD_OVERUSE: 8
};